Updated pic to Base64, Added Nu Validator Link
barrycumbie/dev-challenge-01 pull request #21
Opened 2021-01-22 02:28 UTC by AlphaAndTheOshea

I updated my pic to base 64, I also added a link to Nu Validation of web page.

2021-01-22 02:29 UTC, AlphaAndTheOshea commented
HOLLA AT YA BOI.

2021-01-25 02:00 UTC, AlphaAndTheOshea commented
i should have all objectives completed for Dev-01, and Dev02 now. Please let me know if anything is wrong. @barrycumbie

2021-01-26 19:48 UTC, barrycumbie commented
@AlphaAndTheOshea looks like you are getting the hang of git & github with this nice PR title and using the @ mentions. 

I've got a couple minor things...see my review and then I can approve. So extremely close!

why not give me a link to your active test page here in the comments too?

2021-01-26 19:49 UTC, barrycumbie commented on docs/dev-profile/harris-first.html
> +    <a href="https://validator.w3.org/nu/?doc=https%3A%2F%2Falphaandtheoshea.github.io%2Fdev-challenge-01%2Fdocs%2Fdev-profile%2Fharris-first.html" target="_blank">Nu Html Checker</a>
this needs to point to what your page WILL be when it is merged, so on barrycumbie.github.io (you are setting up a link now for a page that will exist in the future...very trippy)

2021-01-26 19:50 UTC, barrycumbie requested changes
can you remove the index.html from this PR...or initiate another one that just has ONE file?

2021-01-26 19:50 UTC, closed without merging

2021-01-26 20:00 UTC, barrycumbie commented
@AlphaAndTheOshea okay, okay, I see that you combined Dev 01 and Dev 02 into a single PR. Would prefer these to be separate as my earlier comment...

Dev 01 = a PR with just your dev provile
Dov 02 = PR with just than link added in the index.

2021-01-26 21:47 UTC, barrycumbie commented
here is my test page Nu checked: https://validator.w3.org/nu/?doc=https%3A%2F%2Falphaandtheoshea.github.io%2Fdev-challenge-01%2Fdocs%2Fdev-profile%2Fharris-first.html