added a file with my personal html page using N++
barrycumbie/dev-challenge-01 pull request #22
Opened 2021-01-22 04:52 UTC by olivia7n

2021-01-28 20:36 UTC, barrycumbie requested changes

2021-01-28 20:36 UTC, barrycumbie commented on docs/noah-dev-profile/noah-dev-profile.html
> +                <li>GitHub Profile Link: <a href="https://github.com/olivia7n" target="_blank">GitHub</a></li>
plz put your github username in the text of the link too...we are not linking to "Github" in general, but to your user profile

2021-01-28 20:36 UTC, barrycumbie commented on docs/noah-dev-profile/noah-dev-profile.html
> +    <body style="text-align: left; background-color: rgb(260, 100, 200)">
whew, inline style. Prob the only time I'll let you get away with this.

2021-01-28 20:36 UTC, barrycumbie commented on docs/noah-dev-profile/noah-dev-profile.html
> +            <img src= "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAkACQAAD/4QAiRXhpZgAATU0AKgAAAAgAAQESAAMAAAABAAEAAAAAAAD/2wBDAAIBAQIBAQICAgICAgICAwUDAwMDAwYEBAMFBwYHBwcGBwcICQsJCAgKCAcHCg0KCgsMDAwMB
got to finish this out...need that base64 encoding of an image to drop in here. Will be super long.

2021-01-28 20:36 UTC, barrycumbie commented on docs/noah-dev-profile/noah-dev-profile.html
> +                <li>Bill Gates Dancing</li>
can you give us some links to these tools, resources?

2021-01-28 20:37 UTC, barrycumbie commented
@olivia7n not bad, very close. 

Remember to be nice to ol @barrycumbie and provide in the comments here a link to your active test page (your github pages) and a link to the Nu checker for that test page.

2021-01-29 16:50 UTC, olivia7n commented
https://validator.w3.org/nu/?doc=https%3A%2F%2Folivia7n.github.io%2Fdev-challenge-01%2F

Link to nu checker with live address

2021-01-29 16:55 UTC, olivia7n commented
https://olivia7n.github.io/dev-challenge-01/
this is the link github pages gave me, but it doesn't look right

2021-02-01 14:51 UTC, olivia7n commented
https://validator.w3.org/nu/?doc=https%3A%2F%2Folivia7n.github.io%2Fdev-challenge-01%2Fdocs%2Fnoah-dev-profile%2Fnoah-dev-profile.html

here is the updated nu link

2021-02-01 14:52 UTC, olivia7n commented
https://olivia7n.github.io/dev-challenge-01/docs/noah-dev-profile/noah-dev-profile.html

This link works!

2021-02-01 23:30 UTC, barrycumbie commented
@olivia7n so super close...

1. Here's the deal with the proper link to what I call your ```active test page```:  
https://olivia7n.github.io/dev-challenge-01/docs/noah-dev-profile/noah-dev-profile.html
> * notice that it points to your docs/ folder in the URL 'cuz on your gh fork, you chose to deploy from the ```main``` branch vs the ```docs```. No big deal but you do need to notice it. 
> * also, notice that you have to point to the full url (name your .html file) 'cuz the server looks for a page called ```index.html``` 

so, you just need to drop in a link on your dev profile to the nu checker. Here it is pointing to your active test page: 

https://validator.w3.org/nu/?doc=https%3A%2F%2Folivia7n.github.io%2Fdev-challenge-01%2Fdocs%2Fnoah-dev-profile%2Fnoah-dev-profile.html

⚠️ make sure and resolve those errors and warnings (think it is just missing a closing ```>``` on the img 

then, anticipate what that link will be once your page does get published 
> hint: it won't be ```olivia7n``` but it will be ```barrycumbie```
> hint hint: does ```barrycumbie.github.io``` have a ```docs``` in its pathway? 🙅🏼‍♂️

2021-02-02 03:40 UTC, olivia7n commented
Added Nu Checker link and fixed issues with the image tag

2021-02-02 03:41 UTC, olivia7n commented
https://olivia7n.github.io/dev-challenge-01/docs/noah-dev-profile/noah-dev-profile.html

2021-02-02 16:22 UTC, barrycumbie commented
@olivia7n Did I say you were close before? Now you are so so so super very close!

One thing missing on your line 33...this link should point to THE FUTURE. This should point to your dev profile ONCE I MERGE it to my REPO. That will essentially move it from your ```olivia7n.github.io``` to my ```barrycumbie.github.io```

Look at Harris' line 46: https://barrycumbie.github.io/dev-challenge-01/dev-profile/harris-dev-profile.html

2021-02-02 16:23 UTC, barrycumbie approved these changes

2021-02-02 17:16 UTC, olivia7n commented
Changed last little issue with Nu link

2021-02-02 18:43 UTC, barrycumbie commented
I'm gonna approve this even though: 

a) this link don't work:  https://olivia7n.github.io/dev-challenge-01/docs/noah-dev-profile/noah-dev-profile.html 
> hint: not to docs/
b) your Nu link on your page won't work, I bet
> hint: I don't have the docs/ in my URL 

this will be something you gotta fix.

2021-02-02 18:43 UTC, merged