create my profile
barrycumbie/dev-challenge-01 pull request #63
Opened 2021-02-04 21:24 UTC by H4ruk1

2021-02-04 21:26 UTC, barrycumbie requested changes
just missing your github username in text of link

2021-02-04 21:27 UTC, barrycumbie commented
@H4ruk1 don't forget to give me the link to your ```active test site``` and the Nu link to your ```active test site```

for example, look at #20

2021-02-04 21:28 UTC, barrycumbie requested changes

2021-02-04 21:28 UTC, barrycumbie commented on docs/dev-profile/Haruki-dev.html
> +     /body>
missing < on linke 38

2021-02-04 21:28 UTC, barrycumbie commented on docs/dev-profile/Haruki-dev.html
> +        </ul>
don't for get the link to the Nu validation checker.

2021-02-25 19:47 UTC, H4ruk1 commented
@barrycumbie , I just updated index.html file for dev-02.

2021-02-25 21:00 UTC, barrycumbie commented
@H4ruk1 There are 3 links that I need for this assignment, 2 of them in the comments here and 1 in the code 

As a comment: 
1. A link to your active test site: 
2. A link to the nu checker of your active test site (note: this is the one you currently have in your code): https://validator.w3.org/nu/?doc=https%3A%2F%2Fh4ruk1.github.io%2Fdev-challenge-02%2Fdocs%2Fdev-profile%2FHaruki-dev.html

In the code 
3. A link to the nu checker of your profile ONCE IT BECOMES MERGED into our repo. So, you are creating a link that DOES NOT WORK yet BUT WILL WORK after it is merged. 
> hint: it will look like this:
> https://validator.w3.org/nu/?doc=https%3A%2F%2Fh4ruk1.github.io%2Fdev-challenge-02%2Fdocs%2Fdev-profile%2FHaruki-dev.html
> BUT it will not be your username, it will be mine AND my repo doesn't need the ```docs/``` in the URL.

2021-03-02 20:05 UTC, barrycumbie commented
Hey @barrycumbie here is my 

active test site: ...link

nu checker: https://validator.w3.org/nu/?doc=https%3A%2F%2Fh4ruk1.github.io%2Fdev-challenge-02%2Fdocs%2Fdev-profile%2FHaruki-dev.html

2021-03-02 20:15 UTC, H4ruk1 commented
Hey @barrycumbie here is my

active test site: https://h4ruk1.github.io/dev-challenge-02/docs/dev-profile/Haruki-dev.html

nu checker: https://validator.w3.org/nu/?doc=https%3A%2F%2Fh4ruk1.github.io%2Fdev-challenge-02%2Fdocs%2Fdev-profile%2FHaruki-dev.html

2021-03-02 20:29 UTC, barrycumbie commented
@H4ruk1 thank you for the 2 links! You have one more small issue to correct and then you will be done. 

In your code on line 56

```html
   <a href="https://validator.w3.org/nu/?doc=https%3A%2F%2Fh4ruk1.github.io%2Fdev-challenge-02%2Fdocs%2Fdev-profile%2FHaruki-dev.html">Nu validation link</a>
```

you are missing two things. 

1. specify the target, like you did for your GitHub Profile link in line 30

```html
<a href="https://github.com/H4ruk1" target="_blank">H4ruk1 </a>
```

you need to add ```target="_blank"``` to line 56. 

2. A link to the nu checker of your profile ONCE IT BECOMES MERGED into our repo. 
3. 
4. So, you are creating a link that DOES NOT WORK yet BUT WILL WORK after it is merged.

hint: it will look like this:
https://validator.w3.org/nu/?doc=https%3A%2F%2Fh4ruk1.github.io%2Fdev-challenge-02%2Fdocs%2Fdev-profile%2FHaruki-dev.html
BUT it will not be your username, it will be mine AND my repo doesn't need the docs/ in the URL.

2021-03-04 20:47 UTC, merged

2021-03-04 20:48 UTC, barrycumbie commented
hey @H4ruk1 good job...now you can submit this SAME pr for the Dev-02

2021-03-04 21:05 UTC, barrycumbie commented
Congrats, welcome to our REPO as a COLLABORATOR 

![image](https://user-images.githubusercontent.com/22795694/110030207-0ce67f00-7cfb-11eb-95f9-44268a055de6.png)

Don't forget to ACCEPT my invitation via email (check your SPAM if you don't see it)